# Generated by Django 5.2 on 2025-06-13 18:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestion_id', models.UUIDField(db_column='suggestionId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('is_useful', models.BooleanField(db_column='isUseful', default=False)),
                ('author_id', models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Suggestion',
            },
        ),
        migrations.CreateModel(
            name='SuggestionComment',
            fields=[
                ('comment_id', models.UUIDField(db_column='commentId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('author_id', models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('suggestion_id', models.ForeignKey(db_column='suggestionId', on_delete=django.db.models.deletion.DO_NOTHING, to='suggestions.suggestion')),
            ],
            options={
                'db_table': 'Suggestion_Comment',
            },
        ),
        migrations.CreateModel(
            name='SuggestionVote',
            fields=[
                ('vote_id', models.UUIDField(db_column='voteId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('suggestion_id', models.ForeignKey(db_column='suggestionId', on_delete=django.db.models.deletion.DO_NOTHING, to='suggestions.suggestion')),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Suggestion_Vote',
                'unique_together': {('user_id', 'suggestion_id')},
            },
        ),
    ]
