# Generated by Django 5.2 on 2025-06-16 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='author_id',
            field=models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestioncomment',
            name='author_id',
            field=models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestioncomment',
            name='suggestion_id',
            field=models.ForeignKey(db_column='suggestionId', on_delete=django.db.models.deletion.CASCADE, to='suggestions.suggestion'),
        ),
        migrations.AlterField(
            model_name='suggestionvote',
            name='suggestion_id',
            field=models.ForeignKey(db_column='suggestionId', on_delete=django.db.models.deletion.CASCADE, to='suggestions.suggestion'),
        ),
        migrations.AlterField(
            model_name='suggestionvote',
            name='user_id',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
