# Generated by Django 5.2 on 2025-05-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
    ]
