# Generated by Django 4.2.20 on 2025-04-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
        migrations.AlterModelTable(
            name='job',
            table='Job',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
