# Generated by Django 5.2 on 2025-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
