# Generated by Django 5.2 on 2025-05-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job_id', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('name', 'employer_id', 'start_date')},
        ),
    ]
