# Generated by Django 5.2 on 2025-05-23 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_job_duration_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employee_id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='employer_id',
            field=models.ForeignKey(db_column='employerId', default='test', on_delete=django.db.models.deletion.DO_NOTHING, related_name='appications_as_employer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['employer_id'], name='Application_employe_89a396_idx'),
        ),
    ]
