# Generated by Django 5.2 on 2025-05-03 12:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_alter_application_employee_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.TextField(db_column='msgId', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(db_column='isEdited', default=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('last_edited_at', models.DateTimeField(blank=True, db_column='lastEditedAt', null=True)),
                ('application_id', models.ForeignKey(db_column='matchId', on_delete=django.db.models.deletion.DO_NOTHING, to='applications.application')),
                ('reply_to_id', models.ForeignKey(blank=True, db_column='replyToId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='message.message')),
                ('sender_id', models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Messagefile',
            fields=[
                ('message_file_id', models.TextField(db_column='id', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('file_url', models.URLField(db_column='fileUrl')),
                ('file_name', models.TextField(db_column='fileName')),
                ('file_type', models.TextField(db_column='fileType')),
                ('file_size', models.IntegerField(db_column='fileSize')),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('message_id', models.ForeignKey(db_column='messageId', on_delete=django.db.models.deletion.DO_NOTHING, to='message.message')),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messageFile',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['application_id'], name='message_matchId_14d126_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_id'], name='message_senderI_abe533_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to_id'], name='message_replyTo_6815c8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagefile',
            index=models.Index(fields=['message_id'], name='messageFile_message_10ce23_idx'),
        ),
        migrations.AddIndex(
            model_name='messagefile',
            index=models.Index(fields=['user_id'], name='messageFile_userId_83d216_idx'),
        ),
    ]
