# Generated by Django 5.2 on 2025-06-16 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_employee_id_and_more'),
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='application_id',
            field=models.ForeignKey(db_column='applicationId', on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to_id',
            field=models.ForeignKey(blank=True, db_column='replyToId', null=True, on_delete=django.db.models.deletion.CASCADE, to='message.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
