# Generated by Django 5.2 on 2025-05-03 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='messagefile',
            name='messageFile_userId_83d216_idx',
        ),
        migrations.RenameField(
            model_name='messagefile',
            old_name='user_id',
            new_name='sender_id',
        ),
        migrations.AddIndex(
            model_name='messagefile',
            index=models.Index(fields=['sender_id'], name='messageFile_userId_83d216_idx'),
        ),
    ]
