# Generated by Django 5.2 on 2025-06-02 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='Message_applica_74bfa5_idx',
            old_name='Message_matchId_cbac6c_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='application_id',
            field=models.ForeignKey(db_column='applicationId', on_delete=django.db.models.deletion.DO_NOTHING, to='applications.application'),
        ),
    ]
