# Generated by Django 5.2 on 2025-05-30 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('companies', '0001_initial'),
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_key', models.TextField(db_column='fileKey', primary_key=True, serialize=False)),
                ('file_url', models.URLField(db_column='fileUrl')),
                ('file_name', models.TextField(db_column='fileName')),
                ('file_type', models.TextField(db_column='fileType')),
                ('file_size', models.IntegerField(db_column='fileSize')),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('associated_type', models.TextField(choices=[('Message', 'Message'), ('Group Message', 'Group Message'), ('User', 'User'), ('Job', 'Job'), ('Company', 'Company')], db_column='associatedType')),
                ('associated_group_message', models.TextField(blank=True, db_column='associatedGroupMessage', null=True)),
                ('associated_company', models.ForeignKey(blank=True, db_column='associatedCompany', null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.employerprofile')),
                ('associated_job', models.ForeignKey(blank=True, db_column='associatedJob', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.job')),
                ('associated_message', models.ForeignKey(blank=True, db_column='associatedMessage', null=True, on_delete=django.db.models.deletion.PROTECT, to='message.message')),
                ('associated_user', models.ForeignKey(blank=True, db_column='associatedUser', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'File',
                'indexes': [models.Index(fields=['associated_message'], name='File_associa_4f7a9f_idx'), models.Index(fields=['associated_group_message'], name='File_associa_338741_idx'), models.Index(fields=['associated_user'], name='File_associa_6d635f_idx'), models.Index(fields=['associated_job'], name='File_associa_79f7b4_idx'), models.Index(fields=['associated_company'], name='File_associa_94326b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', True), ('associated_job__isnull', True), ('associated_message__isnull', False), ('associated_type', 'Message'), ('associated_user__isnull', True)), models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', False), ('associated_job__isnull', True), ('associated_message__isnull', True), ('associated_type', 'Group Message'), ('associated_user__isnull', True)), models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', True), ('associated_job__isnull', True), ('associated_message__isnull', True), ('associated_type', 'User'), ('associated_user__isnull', False)), models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', True), ('associated_job__isnull', False), ('associated_message__isnull', True), ('associated_type', 'Job'), ('associated_user__isnull', True)), models.Q(('associated_company__isnull', False), ('associated_group_message__isnull', True), ('associated_job__isnull', True), ('associated_message__isnull', True), ('associated_type', 'Company'), ('associated_user__isnull', True)), _connector='OR'), name='files_file_only_one_associated_object')],
            },
        ),
    ]
