# Generated by Django 5.2 on 2025-05-21 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0002_remove_messagefile_messagefile_userid_83d216_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_key', models.TextField(db_column='fileKey', primary_key=True, serialize=False)),
                ('file_url', models.URLField(db_column='fileUrl')),
                ('file_name', models.TextField(db_column='fileName')),
                ('file_type', models.TextField(db_column='fileType')),
                ('file_size', models.IntegerField(db_column='fileSize')),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('associated_type', models.TextField(choices=[('Message', 'Message'), ('Group Message', 'Group Message')], db_column='associatedType')),
                ('associated_group_message', models.TextField(blank=True, db_column='associatedGroupMessage', null=True)),
                ('associated_message', models.ForeignKey(blank=True, db_column='associatedMessage', null=True, on_delete=django.db.models.deletion.PROTECT, to='message.message')),
            ],
            options={
                'db_table': 'files',
                'indexes': [models.Index(fields=['associated_message'], name='files_associa_80689c_idx'), models.Index(fields=['associated_group_message'], name='files_associa_510740_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('associated_group_message__isnull', True), ('associated_message__isnull', False), ('associated_type', 'Message')), models.Q(('associated_group_message__isnull', False), ('associated_message__isnull', True), ('associated_type', 'Group Message')), _connector='OR'), name='files_files_only_one_associated_object')],
            },
        ),
    ]
