# Generated by Django 5.2 on 2025-05-21 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_unique_together_and_more'),
        ('companies', '0004_remove_companyfollow_companyfoll_userid_5cf5ac_idx_and_more'),
        ('files', '0001_initial'),
        ('message', '0002_remove_messagefile_messagefile_userid_83d216_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='files',
            name='files_files_only_one_associated_object',
        ),
        migrations.AddField(
            model_name='files',
            name='associated_company',
            field=models.ForeignKey(blank=True, db_column='associatedCompany', null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.employerprofile'),
        ),
        migrations.AddField(
            model_name='files',
            name='associated_job',
            field=models.ForeignKey(blank=True, db_column='associatedJob', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.job'),
        ),
        migrations.AddField(
            model_name='files',
            name='associated_user',
            field=models.ForeignKey(blank=True, db_column='associatedUser', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='associated_type',
            field=models.TextField(choices=[('Message', 'Message'), ('Group Message', 'Group Message'), ('User', 'User'), ('Job', 'Job'), ('Company', 'Company')], db_column='associatedType'),
        ),
        migrations.AddConstraint(
            model_name='files',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('associated_company__isnull', False), ('associated_group_message__isnull', False), ('associated_job__isnull', False), ('associated_message__isnull', True), ('associated_type', 'Message'), ('associated_user__isnull', False)), models.Q(('associated_company__isnull', False), ('associated_group_message__isnull', True), ('associated_job__isnull', False), ('associated_message__isnull', False), ('associated_type', 'Group Message'), ('associated_user__isnull', False)), models.Q(('associated_company__isnull', False), ('associated_group_message__isnull', False), ('associated_job__isnull', False), ('associated_message__isnull', False), ('associated_type', 'User'), ('associated_user__isnull', True)), models.Q(('associated_company__isnull', False), ('associated_group_message__isnull', False), ('associated_job__isnull', True), ('associated_message__isnull', False), ('associated_type', 'Job'), ('associated_user__isnull', False)), models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', False), ('associated_job__isnull', False), ('associated_message__isnull', False), ('associated_type', 'Company'), ('associated_user__isnull', False)), _connector='OR'), name='files_files_only_one_associated_object'),
        ),
    ]
