# Generated by Django 5.2 on 2025-06-16 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_employee_id_and_more'),
        ('companies', '0002_alter_companyfollow_company_id_and_more'),
        ('files', '0001_initial'),
        ('groups', '0002_alter_group_creator_id_alter_group_job_id_and_more'),
        ('message', '0002_alter_message_application_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='associated_company',
            field=models.ForeignKey(blank=True, db_column='associatedCompany', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.employerprofile'),
        ),
        migrations.AlterField(
            model_name='file',
            name='associated_group_message',
            field=models.ForeignKey(blank=True, db_column='associatedGroupMessage', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupmessage'),
        ),
        migrations.AlterField(
            model_name='file',
            name='associated_job',
            field=models.ForeignKey(blank=True, db_column='associatedJob', null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.job'),
        ),
        migrations.AlterField(
            model_name='file',
            name='associated_message',
            field=models.ForeignKey(blank=True, db_column='associatedMessage', null=True, on_delete=django.db.models.deletion.CASCADE, to='message.message'),
        ),
        migrations.AlterField(
            model_name='file',
            name='associated_user',
            field=models.ForeignKey(blank=True, db_column='associatedUser', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
