# Generated by Django 5.2 on 2025-06-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('groups', '0002_remove_groupmember_group_membe_jobid_b3e9a1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='associated_group_message',
            field=models.ForeignKey(blank=True, db_column='associatedGroupMessage', null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.groupmessage'),
        ),
    ]
