# Generated by Django 5.2 on 2025-05-21 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_unique_together_and_more'),
        ('companies', '0004_remove_companyfollow_companyfoll_userid_5cf5ac_idx_and_more'),
        ('files', '0002_remove_files_files_files_only_one_associated_object_and_more'),
        ('message', '0002_remove_messagefile_messagefile_userid_83d216_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='files',
            name='files_files_only_one_associated_object',
        ),
        migrations.AddConstraint(
            model_name='files',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', True), ('associated_job__isnull', True), ('associated_message__isnull', False), ('associated_type', 'Message'), ('associated_user__isnull', True)), models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', False), ('associated_job__isnull', True), ('associated_message__isnull', True), ('associated_type', 'Group Message'), ('associated_user__isnull', True)), models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', True), ('associated_job__isnull', True), ('associated_message__isnull', True), ('associated_type', 'User'), ('associated_user__isnull', False)), models.Q(('associated_company__isnull', True), ('associated_group_message__isnull', True), ('associated_job__isnull', False), ('associated_message__isnull', True), ('associated_type', 'Job'), ('associated_user__isnull', True)), models.Q(('associated_company__isnull', False), ('associated_group_message__isnull', True), ('associated_job__isnull', True), ('associated_message__isnull', True), ('associated_type', 'Company'), ('associated_user__isnull', True)), _connector='OR'), name='files_files_only_one_associated_object'),
        ),
    ]
