# Generated by Django 5.2 on 2025-05-21 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_unique_together_and_more'),
        ('companies', '0004_remove_companyfollow_companyfoll_userid_5cf5ac_idx_and_more'),
        ('files', '0003_remove_files_files_files_only_one_associated_object_and_more'),
        ('message', '0002_remove_messagefile_messagefile_userid_83d216_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['associated_user'], name='files_associa_6cb826_idx'),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['associated_job'], name='files_associa_7437a5_idx'),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['associated_company'], name='files_associa_a977e0_idx'),
        ),
    ]
