# Generated by Django 5.2 on 2025-06-02 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.TextField(db_column='groupId', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('bio', models.TextField()),
                ('creator_id', models.ForeignKey(db_column='creatorId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('member_id', models.TextField(db_column='memberId', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('group_id', models.ForeignKey(db_column='groupId', on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
                ('job_id', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.DO_NOTHING, to='applications.job')),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Group_Member',
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('message_id', models.TextField(db_column='messageId', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(db_column='isEdited', default=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('last_edited_at', models.DateTimeField(blank=True, db_column='lastEditedAt', null=True)),
                ('group_id', models.ForeignKey(db_column='groupId', on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
                ('reply_to_id', models.ForeignKey(blank=True, db_column='replyToId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.groupmessage')),
                ('sender_id', models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Group_Message',
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['creator_id'], name='Group_creator_156de3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user_id'], name='Group_Membe_userId_347dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group_id'], name='Group_Membe_groupId_12e611_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['job_id'], name='Group_Membe_jobId_b3e9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group_id'], name='Group_Messa_groupId_b41bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['sender_id'], name='Group_Messa_senderI_ef94a6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['reply_to_id'], name='Group_Messa_replyTo_8b7e97_idx'),
        ),
    ]
