# Generated by Django 5.2 on 2025-06-13 18:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(db_column='groupId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bio', models.TextField()),
                ('creator_id', models.ForeignKey(db_column='creatorId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.DO_NOTHING, to='applications.job')),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('member_id', models.UUIDField(db_column='memberId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.TextField(choices=[('Admin', 'Admin'), ('Member', 'Member')])),
                ('group_id', models.ForeignKey(db_column='groupId', on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Group_Member',
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('message_id', models.UUIDField(db_column='messageId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(db_column='isEdited', default=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('last_edited_at', models.DateTimeField(blank=True, db_column='lastEditedAt', null=True)),
                ('group_id', models.ForeignKey(db_column='groupId', on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
                ('reply_to_id', models.ForeignKey(blank=True, db_column='replyToId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.groupmessage')),
                ('sender_id', models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.DO_NOTHING, to='groups.groupmember')),
            ],
            options={
                'db_table': 'Group_Message',
            },
        ),
    ]
