# Generated by Django 5.2 on 2025-06-16 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_employee_id_and_more'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator_id',
            field=models.ForeignKey(db_column='creatorId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='job_id',
            field=models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, to='applications.job'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(db_column='groupId', on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user_id',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group_id',
            field=models.ForeignKey(db_column='groupId', on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='reply_to_id',
            field=models.ForeignKey(blank=True, db_column='replyToId', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupmessage'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender_id',
            field=models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.CASCADE, to='groups.groupmember'),
        ),
    ]
