# Generated by Django 5.2 on 2025-06-02 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='groupmember',
            name='Group_Membe_jobId_b3e9a1_idx',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='job_id',
        ),
        migrations.AddField(
            model_name='group',
            name='job_id',
            field=models.ForeignKey(db_column='jobId', default='test', on_delete=django.db.models.deletion.DO_NOTHING, to='applications.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.TextField(choices=[('Admin', 'Admin'), ('Member', 'Member')]),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender_id',
            field=models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.DO_NOTHING, to='groups.groupmember'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['job_id'], name='Group_jobId_62f3b5_idx'),
        ),
    ]
