# Generated by Django 5.2 on 2025-05-07 08:31

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employerprofile',
            fields=[
                ('company_id', models.TextField(db_column='id', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('company_name', models.TextField(blank=True, db_column='companyName', null=True)),
                ('company_website', models.TextField(blank=True, db_column='companyWebsite', null=True)),
                ('contact_name', models.TextField(blank=True, db_column='contactName', null=True)),
                ('contact_role', models.TextField(blank=True, db_column='contactRole', null=True)),
                ('company_size', models.TextField(blank=True, db_column='companySize', null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('talent_needs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_column='talentNeeds', null=True, size=None)),
                ('work_style', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_column='workStyle', null=True, size=None)),
                ('hiring_timeline', models.TextField(blank=True, db_column='hiringTimeline', default=False, null=True)),
                ('featured_partner', models.BooleanField(db_column='featuredPartner')),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('image', models.URLField(blank=True, null=True)),
                ('employer_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmployerProfile',
            },
        ),
        migrations.CreateModel(
            name='Companyfollow',
            fields=[
                ('follow_id', models.TextField(db_column='id', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.employerprofile')),
            ],
            options={
                'db_table': 'companyFollow',
            },
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['employer_id'], name='EmployerPro_userId_7c7a04_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfollow',
            index=models.Index(fields=['user_id'], name='companyFoll_userId_5cf5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfollow',
            index=models.Index(fields=['company_id'], name='companyFoll_company_40d0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfollow',
            index=models.Index(fields=['user_id', 'company_id'], name='companyFoll_userId_68da50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfollow',
            unique_together={('user_id', 'company_id')},
        ),
    ]
