# Generated by Django 5.2 on 2025-06-13 15:53

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('company_id', models.UUIDField(db_column='companyId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_name', models.TextField(db_column='companyName')),
                ('company_website', models.URLField(db_column='companyWebsite')),
                ('contact_name', models.TextField(blank=True, db_column='contactName', null=True)),
                ('contact_role', models.TextField(blank=True, db_column='contactRole', null=True)),
                ('company_size', models.TextField(blank=True, db_column='companySize', null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('talent_needs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_column='talentNeeds', null=True, size=None)),
                ('work_style', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_column='workStyle', null=True, size=None)),
                ('hiring_timeline', models.TextField(blank=True, db_column='hiringTimeline', null=True)),
                ('featured_partner', models.BooleanField(db_column='featuredPartner', default=False)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('employer_id', models.ForeignKey(db_column='employerId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Employer_Profile',
                'unique_together': {('employer_id', 'company_name', 'company_website')},
            },
        ),
        migrations.CreateModel(
            name='CompanyFollow',
            fields=[
                ('follow_id', models.UUIDField(db_column='followId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('follower_id', models.ForeignKey(db_column='followerId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.employerprofile')),
            ],
            options={
                'db_table': 'Company_Follow',
                'unique_together': {('follower_id', 'company_id')},
            },
        ),
    ]
