# Generated by Django 5.2 on 2025-05-08 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='image',
            field=models.URLField(blank=True, db_column='image', null=True),
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.TextField(db_column='companyName', default='test_company_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_website',
            field=models.TextField(db_column='companyWebsite', default='test_company_website'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='featured_partner',
            field=models.BooleanField(db_column='featuredPartner', default=False),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='hiring_timeline',
            field=models.TextField(blank=True, db_column='hiringTimeline', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employerprofile',
            unique_together={('employer_id', 'company_name', 'company_website')},
        ),
    ]
