# Generated by Django 5.2 on 2025-06-16 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfollow',
            name='company_id',
            field=models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, to='companies.employerprofile'),
        ),
        migrations.AlterField(
            model_name='companyfollow',
            name='follower_id',
            field=models.ForeignKey(db_column='followerId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_id',
            field=models.ForeignKey(db_column='employerId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
