# Generated by Django 5.2 on 2025-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_employerprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_website',
            field=models.URLField(db_column='companyWebsite'),
        ),
    ]
