# Generated by Django 5.2 on 2025-05-11 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_employerprofile_company_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companyfollow',
            name='companyFoll_userId_5cf5ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='companyfollow',
            name='companyFoll_userId_68da50_idx',
        ),
        migrations.RenameField(
            model_name='companyfollow',
            old_name='user_id',
            new_name='follower_id',
        ),
        migrations.AlterUniqueTogether(
            name='companyfollow',
            unique_together={('follower_id', 'company_id')},
        ),
        migrations.AddIndex(
            model_name='companyfollow',
            index=models.Index(fields=['follower_id'], name='companyFoll_userId_5cf5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfollow',
            index=models.Index(fields=['follower_id', 'company_id'], name='companyFoll_userId_68da50_idx'),
        ),
    ]
