# Generated by Django 5.2 on 2025-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_companyfollow_companyfoll_userid_5cf5ac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='image_url',
        ),
    ]
