# Generated by Django 5.2 on 2025-06-13 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('requirement_id', models.UUIDField(db_column='requirementId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('job_id', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.DO_NOTHING, to='applications.job')),
            ],
            options={
                'db_table': 'Job_Requirement',
            },
        ),
    ]
