# Generated by Django 5.2 on 2025-06-13 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('time_id', models.UUIDField(db_column='timeId', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='startTime')),
                ('end_time', models.DateTimeField(db_column='endTime')),
                ('title', models.TextField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(db_column='employeeId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Timing',
                'unique_together': {('start_time', 'end_time', 'employee_id')},
            },
        ),
    ]
