# Generated by Django 5.2 on 2025-05-07 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0002_alter_timings_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timings',
            unique_together={('start_time', 'end_time', 'employee_id')},
        ),
    ]
