# Generated by Django 5.2 on 2025-05-30 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.TextField(db_column='interestId', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Interest',
                'indexes': [models.Index(fields=['user_id'], name='Interest_userId_bd4e34_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.TextField(db_column='skillId', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Skill',
                'indexes': [models.Index(fields=['user_id'], name='Skill_userId_2776f4_idx')],
            },
        ),
    ]
